<<<<<<< HEAD
# Generated by Django 5.1.4 on 2024-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone_no3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
=======
# Generated by Django 5.1.4 on 2024-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone_no3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
>>>>>>> ac5ee3b06f8168cf659365588c193e4a1d2ef6e9
