<<<<<<< HEAD
# Generated by Django 5.1.4 on 2024-12-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_phone_no3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone_no3',
        ),
    ]
=======
# Generated by Django 5.1.4 on 2024-12-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_phone_no3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone_no3',
        ),
    ]
>>>>>>> ac5ee3b06f8168cf659365588c193e4a1d2ef6e9
