# Generated by Django 5.1.4 on 2025-01-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
    ]
