# Generated by Django 5.1.4 on 2024-12-17 08:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_company_phone_no3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.generate_unique_filename),
        ),
    ]
