# Generated by Django 5.1.4 on 2025-01-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscribers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
