<<<<<<< HEAD
# Generated by Django 5.1.4 on 2024-12-17 08:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.MediaStorage(), upload_to=accounts.models.generate_unique_filename),
        ),
    ]
=======
# Generated by Django 5.1.4 on 2024-12-17 08:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.MediaStorage(), upload_to=accounts.models.generate_unique_filename),
        ),
    ]
>>>>>>> ac5ee3b06f8168cf659365588c193e4a1d2ef6e9
