 
# Generated by Django 5.1.4 on 2024-12-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_date_joined_company_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
 