# Generated by Django 5.1.4 on 2024-12-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_superuser',
        ),
    ]
