# Generated by Django 5.1.4 on 2025-01-13 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
    ]
