# Generated by Django 5.1.4 on 2025-01-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_subscribers_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
