# Generated by Django 5.1.4 on 2024-12-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_users_delete_outstandingtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
