# Generated by Django 5.1.4 on 2025-01-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_subscribers_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
