# Generated by Django 5.1.4 on 2025-01-02 05:34

import company.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eio', models.CharField(blank=True, max_length=50, null=True)),
                ('target', models.CharField(blank=True, max_length=50, null=True)),
                ('results', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('On Going', 'On Going'), ('Achieved', 'Achieved'), ('Not Achieved', 'Not Achieved'), ('Modified', 'Modified')], default='On Going', max_length=20)),
                ('eio_title', models.CharField(blank=True, max_length=50, null=True)),
                ('associated_objective', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_attachment', models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename_audit)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_energy_improvements', to='company.users')),
            ],
        ),
    ]
