# Generated by Django 5.1.4 on 2024-12-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_users_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='confirm_email',
        ),
    ]
