# Generated by Django 5.1.4 on 2025-01-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_correctiveaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='action_corrections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
