# Generated by Django 5.1.4 on 2025-01-02 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_correctiveaction_action_corrections_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_raised', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], default='Pending', max_length=20)),
                ('action', models.TextField(blank=True, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.users')),
            ],
        ),
    ]
