# Generated by Django 5.1.4 on 2024-12-27 10:30

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_employeesurvey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('YouTube video', 'YouTube video'), ('Presentation', 'Presentation'), ('Web Link', 'Web Link')], max_length=255)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename)),
                ('web_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='policydocumentation',
            name='energy_policy',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='policydocumentation',
            name='environmental_policy',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='policydocumentation',
            name='health_safety_policy',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='policydocumentation',
            name='integrated_policy',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='policydocumentation',
            name='quality_policy',
            field=models.FileField(blank=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='training',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
    ]
