# Generated by Django 5.1.4 on 2024-12-27 10:32

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_awarenesstraining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarenesstraining',
            name='web_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='policydocumentation',
            name='energy_policy',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='policydocumentation',
            name='environmental_policy',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='policydocumentation',
            name='health_safety_policy',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='policydocumentation',
            name='integrated_policy',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='policydocumentation',
            name='quality_policy',
            field=models.FileField(blank=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='training',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename),
        ),
    ]
