# Generated by Django 5.1.4 on 2024-12-31 03:39

import company.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_awarenesstraining_web_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='awarenesstraining',
            name='upload_file',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename1),
        ),
        migrations.AlterField(
            model_name='training',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename_training),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_type', models.CharField(choices=[('Normal', 'Normal'), ('Specific', 'Specific')], max_length=50)),
                ('venue', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('send_notification', models.BooleanField(default=False)),
                ('agenda', models.ManyToManyField(blank=True, related_name='agenda', to='company.agenda')),
                ('attendees', models.ManyToManyField(blank=True, related_name='meeting_attendees', to='company.users')),
                ('called_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.users')),
            ],
        ),
    ]
