# Generated by Django 5.1.4 on 2025-01-02 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_targetsp_tprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConformityCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('Audit', 'Audit'), ('Customer', 'Customer'), ('Internal', 'Internal'), ('Supplier', 'Supplier')], max_length=255, null=True)),
                ('ncr', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_raised', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Deleted', 'Deleted')], default='Pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.users')),
                ('root_cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.conformitycause')),
            ],
        ),
    ]
