# Generated by Django 5.1.4 on 2024-12-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_agenda_alter_awarenesstraining_upload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Specific', 'Specific')], default='Normal', max_length=50),
        ),
    ]
