# Generated by Django 5.1.4 on 2024-12-31 04:01

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_meeting_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='minutes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_attached',
            field=models.FileField(blank=True, null=True, storage=company.models.MediaStorage(), upload_to=company.models.generate_unique_filename_minute),
        ),
    ]
