# Generated by Django 5.1.4 on 2024-12-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_meeting_minutes_meeting_minutes_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
