# Generated by Django 5.1.4 on 2024-12-31 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_carnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalproblems',
            name='corrections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalproblems',
            name='no_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.carnumber'),
        ),
        migrations.AlterField(
            model_name='carnumber',
            name='root_cause',
            field=models.CharField(blank=True, choices=[('Audit', 'Audit'), ('Presentation', 'Presentation'), ('Web Link', 'Web Link')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carnumber',
            name='source',
            field=models.CharField(blank=True, choices=[('Audit', 'Audit'), ('Presentation', 'Presentation'), ('Web Link', 'Web Link')], max_length=255, null=True),
        ),
    ]
