# Generated by Django 5.1.4 on 2024-12-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_internalproblems_corrections_internalproblems_no_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnumber',
            name='action_or_corrections',
            field=models.TextField(blank=True, null=True),
        ),
    ]
