# Generated by Django 5.1.4 on 2024-12-31 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_carnumber_action_or_corrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnumber',
            name='root_cause',
            field=models.CharField(blank=True, choices=[('Test', 'Test')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('audit_from', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('certification_body', models.CharField(blank=True, max_length=50, null=True)),
                ('audit_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=50)),
                ('procedures', models.CharField(blank=True, choices=[('Test', 'Test')], max_length=255, null=True)),
                ('date_conducted', models.DateField(blank=True, null=True)),
                ('audit_from_internal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.users')),
            ],
        ),
    ]
