# Generated by Django 5.1.4 on 2024-12-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_audit_upload_audit_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='audit_from_internal',
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_from_internal',
            field=models.ManyToManyField(null=True, related_name='users', to='company.users'),
        ),
    ]
