# Generated by Django 5.1.4 on 2024-12-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
