# Generated by Django 5.1.4 on 2024-12-31 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('corrections', models.CharField(blank=True, max_length=50, null=True)),
                ('solved_after_action', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50)),
                ('immediate_action', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('corrective_action_need', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50)),
                ('category', models.ManyToManyField(blank=True, related_name='category', to='company.category')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.customer')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.users')),
                ('no_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.carnumber')),
            ],
        ),
    ]
