from django.urls import path
from  .views import *

urlpatterns = [
    
    path('company/login/', CompanyLoginView.as_view(), name='company-login'),
    path('users/', UserList.as_view(), name='user-list'), 
    path('users/create/', UserCreate.as_view(), name='user-create'), 
    path('users/<int:pk>/', UserDetail.as_view(), name='user-detail'),   
    path('users/update/<int:pk>/', UserUpdate.as_view(), name='user-update'),   
    path('users/delete/<int:pk>/', UserDelete.as_view(), name='user-delete'),
    path('documentation/', PolicyDocumentationListView.as_view(), name='documentation-list'),  
    path('documentation/<int:pk>/', PolicyDocumentationDetailView.as_view(), name='documentation-detail'),  
    path('documentation/create/', PolicyDocumentationCreateView.as_view(), name='documentation-create'),  
    path('documentation/<int:pk>/update/', PolicyDocumentationUpdateView.as_view(), name='documentation-update'),  
    path('documentation/<int:pk>/delete/', PolicyDocumentationDeleteView.as_view(), name='documentation-delete'),
    path('trainings/add/', AddTrainingView.as_view(), name='add-training'),  
    path('trainings/', TrainingListView.as_view(), name='training-list'),  
    path('trainings/<int:pk>/', TrainingDetailView.as_view(), name='training-detail'), 
    path('trainings/<int:pk>/edit/', EditTrainingView.as_view(), name='edit-training'),  
    path('trainings/<int:pk>/delete/', DeleteTrainingView.as_view(), name='delete-training'),  
    path('user-trainings/<int:user_id>/', UserTrainingListView.as_view(), name='user-trainings'),
    path('user-evaluation/<int:user_id>/', UserTrainingEvaluationView.as_view(), name='user-trainings'),
    path('employee-evaluation/', EmployeeEvaluationListView.as_view(), name='employee-evaluation-list'),
    path('employee-evaluation/add/', EmployeeEvaluationCreateView.as_view(), name='employee-evaluation-add'),
    path('employee-evaluation/<int:pk>/', EmployeeEvaluationDetailView.as_view(), name='employee-evaluation-detail'),
    path('employee-evaluation/<int:pk>/update/', EmployeeEvaluationUpdateView.as_view(), name='employee-evaluation-update'),
    path('employee-evaluation/<int:pk>/delete/', EmployeeEvaluationDeleteView.as_view(), name='employee-evaluation-delete'),
    path('employee-survey/', EmployeeSurveyListView.as_view(), name='employee-evaluation-list'),
    path('employee-survey/add/', EmployeeSurveyCreateView.as_view(), name='employee-evaluation-add'),
    path('employee-survey/<int:pk>/', EmployeeSurveyDetailView.as_view(), name='employee-evaluation-detail'),
    path('employee-survey/<int:pk>/update/', EmployeeSurveyUpdateView.as_view(), name='employee-evaluation-update'),
    path('employee-survey/<int:pk>/delete/', EmployeeSurveyDeleteView.as_view(), name='employee-evaluation-delete'),
    path('awareness-create/', AwarenessCreateView.as_view(), name='employee-evaluation-list'),
    path('awareness/', AwarenessListView.as_view(), name='employee-evaluation-add'),
    path('awareness/<int:pk>/', AwarenessDetailView.as_view(), name='employee-evaluation-detail'),
    path('awareness/<int:pk>/update/', AwarenessUpdateView.as_view(), name='employee-evaluation-update'),
    path('awareness/<int:pk>/delete/', AwarenessDeleteView.as_view(), name='employee-evaluation-delete'),
    path('agendas/', AgendaListCreateView.as_view(), name='agenda-list-create'),   
    path('agendas/<int:pk>/', AgendaDetailView.as_view(), name='agenda-detail'),
    path('meetings/', MeetingListCreateView.as_view(), name='meeting-list-create'), 
    path('meetings/<int:pk>/', MeetingDetailView.as_view(), name='meeting-detail'),
    path('causes/', CauseListCreateView.as_view(), name='agenda-list-create'),   
    path('causes/<int:pk>/', CauseDetailView.as_view(), name='agenda-detail'),
    path('internal-problems/', InternalProblemsListCreateView.as_view(), name='internal-problems-list-create'),
    path('internal-problems/<int:pk>/', InternalProblemsDetailView.as_view(), name='internal-problems-detail'),
    path('car-numbers/', CarNumberListCreateView.as_view(), name='car-number-list-create'),
    path('car-numbers/<int:pk>/', CarNumberDetailView.as_view(), name='car-number-detail'),
    path('audits/', AuditListCreateView.as_view(), name='audit-list-create'),
    path('audits/<int:pk>/', AuditDetailView.as_view(), name='audit-detail'),
    path('inspections/', InspectionListCreate.as_view(), name='inspection-list-create'),
    path('inspections/<int:pk>/', InspectionRetrieveUpdateDelete.as_view(), name='inspection-retrieve-update-delete'),
    path('customer/', CustomerListCreate.as_view(), name='inspection-list-create'),
    path('customer/<int:pk>/', CustomerRetrieveUpdateDelete.as_view(), name='inspection-retrieve-update-delete'),
    path('category/', CategoryListCreateView.as_view(), name='agenda-list-create'),   
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='agenda-detail'),
]

